package au.com.agiledigital.toolform.app

import java.io.File

import au.com.agiledigital.toolform.version.BuildInfo
import org.scalatest.{FlatSpec, Matchers}

import scala.io.Source

class GenerateTaskTest extends FlatSpec with Matchers {

  val testFile = pathToFile("/test_project/environment.conf")

  def pathToFile(pathToFile: String): File = {
    val url  = getClass.getResource(pathToFile)
    val file = new File(url.toURI())
    file
  }

  "generate" should "generate a valid Docker Compose v3 file" in {
    val outputFile = File.createTempFile(getClass.getName, ".yaml")
    outputFile.deleteOnExit()
    ToolFormApp.execute(List("generate", "-i", testFile.getAbsolutePath, "-o", outputFile.getAbsolutePath).toArray)
    val result = Source.fromFile(outputFile.getAbsolutePath).mkString
    result should equal(s"""# Generated by ${BuildInfo.name} (${BuildInfo.version})
          |version: '3'
          |  services:
          |    seswipmainpublicapinginx:
          |      image: se_swip_main_public_api_nginx
          |      restart: always
          |      ports:
          |      - "80:80"
          |    publicapi:
          |      image: se_swip/public_api
          |      restart: always
          |      labels:
          |        source.path: "server/public"
          |        project.artefact: "true"
          |    seswipelasticsearch:
          |      image: se_swip/se_swip_elastic_search
          |      restart: always
          |      labels:
          |        source.path: "resources/elastic_search"
          |        project.artefact: "true"
          |    seswipinfluxdb:
          |      image: se_swip/se_swip_influx_db
          |      restart: always
          |      labels:
          |        source.path: "resources/influxdb"
          |        project.artefact: "true"
          |    clientpublic:
          |      image: se_swip/client/public
          |      restart: always
          |      labels:
          |        source.path: "client/public"
          |        project.artefact: "true"
          |    seswipcarbon:
          |      image: se_swip/se_swip_carbon
          |      restart: always
          |    seswipmailrelay:
          |      image: se_swip/se_swip_mail_relay
          |      restart: always
          |    seswipdb:
          |      image: se_swip/se_swip_db
          |      restart: always
          |""".stripMargin)
  }
}
